### PR TITLE
bugfix: download of crate does not work after multiple versions has been published

### LINKED ISSUE #18: Not possible to retrieve artifacts back after multiple versions were published
* **What are you trying to do?**

Use the repository after publishing multiple versions of the same artifact

* **What feature or behavior is this required for?**

Successful long-term usage of the repo

* **How could we solve this issue? (Not knowing is okay!)**

By uncovering the root cause

* **Anything else?**

Reproducible steps:

1. Start the repo locally: `docker build -t nexus-repository-cargo .` then `docker run --rm -p 8081:8081 --name nexus-repository-cargo nexus-repository-cargo`
2. Do the initial setup (admin password; configure crate realm; create a repo of type `cargo` - say, named, `crates-snapshot` and obtain a token for publishing - by calling `/repository/crates-snapshot/token` endpoint)
3. Obtain a Rust crate to publish
4. `cargo publish` the crate into local repo
5. modify the version of the crate to be version + 1 patch
6. attempt to clone the index `git clone http://localhost:8081/repository/crates-snapshot/index`
7. repeat steps 4 to 6 until step 6 fails with 500 server error and the attached [stacktrace.log](https://github.com/sonatype-nexus-community/nexus-repository-cargo/files/7596795/stacktrace.log) shows up in the Nexus logs

### PR DESCRIPTION
**Pull request by bguerin**
* Fixes #18

### CODE REVIEW

**Comment by ethill-pulse** [comment]
Is there any reason this hasn't been merged? @bguerin's fork seems very ahead of the community repo in some important ways.

**Comment by peterrojs** [comment]
@bhamail could this and some other PRs be merged? The project seems a bit stale at the moment

**Comment by bhamail** [comment]
@peterrojs @bguerin Oh wow, I didn't realize how long some of these have been out there! I'm no longer working on these projects regularly, and I'm no Nexus Repository expert. That said, I'll try to get some of these PR's merged in, with the warning that I ask y'all to please holler loudly if something breaks - as I can't dedicate my usual level effort to testing the changes.

**Review by bhamail — APPROVED** [review]
+1. Honestly not sure I follow what's happening here, but I don't want my ignorance to stand in the way of progress. Holler if problem arise! Thanks for all your work!!!

**Comment by peterrojs** [comment]
Thank you so much!!

**Comment by bguerin** [comment]
> Honestly not sure I follow what's happening here

from what I remember, it is a story of transaction that need to be opened and kept opened to retrieve one after the other the informations of the crate and its content
This fix what inspired by what is done in Debian packages Repository handling

**Pull request merged**
